### ISSUE TITLE
Mouse can leave fullscreen window

### ISSUE THREAD

**Issue by psypherium** [viewizard/astromenace#1]
When playing on a dual-monitor setup, the mouse cursor can leave the fullscreen window and interact with windows on the other monitor. I don't know if this will be easy to fix, it's not a big problem anyway. Just thought I would let you know. I hope you have a good day.

Expected behavior: mouse should only leave window when it isn't attached to ship control. When there is a cursor on the screen, it can leave the window, that's fine. When there is no cursor on the screen and my mouse is controlling the ship, the input should be locked within the window.

Arch
AMDGPU-all-open
Gnome3

**Comment by viewizard** [comment]
I see the issue. I grab mouse only for windowed mode.
Will be fixed.

**Comment by psypherium** [comment]
Perfect, no more problem! Nice work! :+1:
