### ISSUE TITLE
Incorrect locale handling

### ISSUE THREAD

**Issue by AMDmi3** [viewizard/astromenace#13]
My locale settings:

```
% locale
LANG=ru_RU.UTF-8
LC_CTYPE="ru_RU.UTF-8"
LC_COLLATE=C
LC_TIME=C
LC_NUMERIC="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES=C
LC_ALL=
```

This is tuned in a way that applications would handle Russian properly (LC_CTYPE), but interface would stay unlocalized (LC_MESSAGES). Astromenace runs in Russian, so it reads locale settings incorrectly. LC_MESSAGES is the locale entity responsible for the UI language, so taking standard locale selection logic, it should act as follows:

- if LC_ALL is defined, take UI language from LC_ALL (e.g. LC_ALL overrides everything)
- otherwise, if LC_MESSAGES is defined, take UI language from LC_MESSAGES
- otherwise, if LANG is defined, take UI language from LANG (e.g. LANG is the default for all LC_* aspects)
- otherwise, fallback to default (English)

**Comment by viewizard** [comment]
For now we use LC_ALL > LANG  for language detection. Will fix it for LC_ALL > LC_MESSAGES > LANG. Thanks!

**Comment by viewizard** [comment]
Fixed https://github.com/viewizard/astromenace/commit/baa20d568ad92049e314d7651c70da03258c6bc5

**Comment by AMDmi3** [comment]
Confirmed.
