### ISSUE TITLE
The Spaceship cannot move using the keyboard.

### ISSUE THREAD

**Issue by blaine12100** [viewizard/astromenace#16]
## Expected Behavior
They spaceship should move in the up/down/left/right when the up/down/left/right arrow key is pressed

## Actual Behavior
Nothing happens.I can fire both my weapons but the ship is fixed in one place

## Steps to Reproduce the Problem

  1.Install a Clean Copy of Astromenance
  2.Launch the first mission
  3.The ship does not move

## Specifications

  - Operating System (with version, if you know it):Ubuntu 18.04
    * For example: Windows 10 Home / macOS 10.9 / Ubuntu 18.04
  - Hardware Specifications (optional, if you know it):Intel core i7,Nvidia Geforce 840M,8 GB RAM
    * For example: Intel i7 8500, 8GB memory, Nvidia 760 GTX with 2GB memory
  - Video Drivers (optional, if you know it):
    * For example: Nvidia drivers 390.42 / xf86-video-amdgpu 18.0.1
  - Game Version:Version 1.3.2
    * You can find it in the left bottom corner in the game menu.
  - Git Commit (optional, for test/self made builds only):

## Game Configuration (optional)

Please provide your AstroMenace game configuration (config.xml and PilotsProfiles_N.N.data, where N is number).

Files location:
  - Windows: C:\\Users\\{user name}\\AppData\\Roaming\\Viewizard\\AstroMenace\\
  - Linux: ~/.config/astromenace/

Note, these are plain text files, you could use https://gist.github.com/ (or any other service) and provide links, or change the files' extensions to '.txt' in order to attach them directly to the Issue.

Please, DO NOT copy files content to the Issue itself.

## Terminal Output (optional, Linux)

Launch AstroMenace from terminal with logging into file. For example:

```$ ./astromenace > ~/Desktop/log.txt```

log.txt on your Desktop is the result.

You could use https://gist.github.com/ (or any other service) and provide a link, or attach the file directly to the Issue.

Please, DO NOT copy file content to the Issue itself.

**Comment by viewizard** [comment]
Could you change movement keys in Astromenace menu to WASD, for example, and test ship movement?

**Comment by blaine12100** [comment]
I replaced the keys with WASD or Num 8,Num 2,Num 4,Num 1 but the spaceship still did not move.

**Comment by viewizard** [comment]
Could you please test with <MouseControl value="off" />?
Open the game config file (~/.config/astromenace/amconfig.xml) and change this parameter to off. As I see in the code, only mouse events could block movement keys status. Note, you will be still able to navigate with mouse in menu, but ship control by mouse will be disabled.

**Comment by blaine12100** [comment]
HI

Thanks for the suggestion.The game does work now as intended.It's really fun to be honest.
Can you include this suggestion in the Readme so the users can be better informed regarding this?
