### ISSUE TITLE
Website: Screenshots page is absent

### ISSUE THREAD

**Issue by tehnick** [viewizard/astromenace#17]
Could you add a separate Screenshots page to your website?
So I will be able to point to this page here:
https://salsa.debian.org/games-team/astromenace/blob/master/debian/upstream/metadata
Some details about Debian upstream metadata you may find here:
https://wiki.debian.org/UpstreamMetadata

**Comment by viewizard** [comment]
Sure, I will care about this on weekend. I just need create some screenshots.

**Comment by viewizard** [comment]
I added new screenshots page with widescreen screenshots:
https://viewizard.com/screenshots.html

Hope, this helps.

**Comment by tehnick** [comment]
> I added new screenshots page with widescreen screenshots:
> https://viewizard.com/screenshots.html

Perfect! Thanks!

> Hope, this helps.

And the last step would be adding of hyperlink to that page from the main page (or any other page by your choice).

=)
