### ISSUE TITLE
Latest releases are absent on SourceForge

### ISSUE THREAD

**Issue by tehnick** [viewizard/astromenace#18]
Unfortunately I have missed latest releases of your game because they were not uploaded to https://sourceforge.net/projects/openastromenace/files/ where Debian infrastructure was looking for updates.

I will use this git repo for the future updates of Debian package. But probably it would be a good idea to keep SourceForge project in sync with GitHub. Just in case.

**Comment by viewizard** [comment]
Added files for v1.4.0 and v1.4.1. Added github integration, all future releases will be added to SF automatically. Thanks for advice!
