### ISSUE TITLE
Can't open game

### ISSUE THREAD

**Issue by AlejandroFNadal** [viewizard/astromenace#19]
The game does not open for some reason

## Actual Behavior
error: XDG_RUNTIME_DIR not set in the environment.
main(): Couldn't init SDL: No available video device

## Steps to Reproduce the Problem
I just cloned the repo and followed the steps that you wrote
## Specifications

  - Operating System (with version, if you know it):Debian 10
    * For example: Windows 10 Home / macOS 10.9 / Ubuntu 18.04
  - Hardware Specifications (optional, if you know it):12 GB RAM, Integrated videocard, I7 7th generation, notebook HP
    
I would really love to play your game, I hope you can help me

**Comment by viewizard** [comment]
Hi,
```
error: XDG_RUNTIME_DIR not set in the environment.
main(): Couldn't init SDL: No available video device
```
let me think, that you have some kind of issue not related to game, but related to SDL.
Are you able to start the game outside of terminal, for example, by custom launcher in your DE?
Are you able to start any 3D game?
