### ISSUE TITLE
1.4.2 release?

### ISSUE THREAD

**Issue by AMDmi3** [viewizard/astromenace#30]
There's 1.4.2-1781 tag in the repository. Is this a new official release? If so, why's it not mentioned on https://viewizard.com/download.html?

**Comment by viewizard** [comment]
This is auto generated by CI pre-release for testing only, see:
https://github.com/viewizard/astromenace/releases

github can't create pre-release without tag, I have nothing to do with this.

**Comment by AMDmi3** [comment]
Got it, thanks!
