### ISSUE TITLE
How to play the game

### ISSUE THREAD

**Issue by WilliamWangPeng** [viewizard/astromenace#31]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![微信图片_20210406222300](https://user-images.githubusercontent.com/51076736/113726610-f5018100-9726-11eb-8259-fd4b463da091.png)

thank you  
best regards to you  
William

**Comment by viewizard** [comment]
Hello,
Looks like all works.
"Create" button will be unlocked as soon as you type at least one character in "New pilot profile". Rest buttons will be unlocked as soon, as you create profile.

**Comment by WilliamWangPeng** [comment]
> Hello,
> Looks like all works.
> "Create" button will be unlocked as soon as you type at least one character in "New pilot profile". Rest buttons will be unlocked as soon, as you create profile.

hi dear @viewizard    
    I have played this game whichi si truly fantanstic, and nowadays the most important thing to me is to analysis the rendering method in this game, like rasterization or ray tracing method, or other computer graphics  methods or algorithms?  

thank you  
best regards  
William
