### ISSUE TITLE
how to install languages

### ISSUE THREAD

**Issue by atesin** [viewizard/astromenace#32]
## Expected Behavior
the game is in english but i wish put in spanish, luckly i realised there are translations available at crowdin

## Actual Behavior
- there is no indication anywhere on how to install the translation file
- i cant download the file from crowdin FREELY (as "libre", not as "gratis") because it obligues me to login before. according the gplv3 in which code and assets are licensed (according LICENSE.md file), it shouldn't impose any restriction or constraint to access sources 

## Steps to Reproduce the Problem
- try to download the translation file directly and anonymously, and i cant (i love my privacy and my free will)
- even if i would have the file, i haven't found any instruction on how to install and make it work with the game

## Specifications
i think my pc specs are meaningless in this case because the game runs me marvelous and i just want to switch the language (i am chilean), but anyway i have:
- astromenace 1.4.1 for windows, downloaded directly from your website
- windows 8.1 x64 spanish (dont like 10, i like 7 but now is a bit outdated)
- dell precision t7500 (intel pentium xeon 3.5ghz, 12gb ram, 1tb sata hd, dvd recorder, hd audio, gigabit lan, etc)
- nvidia geforce gtx1650 4gb gddr5
- standard 1080p monitor, keyboard and mouse, etc.

this game likes me a lot... i hope you document how to localize the game, and do something with the register/login requirements to download the translations

**Comment by viewizard** [comment]
Hello,
you can download last build of translation file without login on Crowdin:
![Screenshot 2021-08-29 124808](https://user-images.githubusercontent.com/15098562/131246222-f5071ea7-7d5b-4b3b-8a2d-101ccabe488b.png)
this is the same file as we have in git `gamedata/lang/text.csv`.
Note, Crowdin not part of our CI/CD, this is just standalone service that we use for translation help.

You could clone git repo and replace `gamedata/lang/text.csv` file if you want. CVS file could be open by LibreOffice Calc, for example. You could change this file text.csv with translation you want and rebuild the game.
Note, for full language support voice and some pictures should be provided too (see `gamedata/lang` folder for example).

**Comment by atesin** [comment]
hi, thanks for take the time to answer
i know how to download files, it is trivial... i mean another issue
i mean, when i click the download link, instead of start downloading the file it redirects me to a login form... every time... and it shouldn't be like that, but download the file with no conditions instead

self answer: instead click the "lang.csv" filename (dont do it, is for file edition), you can also click the corner cloud+arrows icon (like github)... you could include these directions in docs to help others too
![image](https://user-images.githubusercontent.com/8086106/131296476-2fa4a6e2-4071-45a4-a89e-7a161a2527cd.png)


ok now that i have the file... i can't see any lang/ subfolder inside my instalation folder (in fact all files are there and there are no subfolders at all)...  do you mean i have to download sources and compile the game?... why dont make the game read the file at runtime as some other games/apps do?, would be a lot easier for us the users, especially for non experimented ones
dont you? :)
