### ISSUE TITLE
Game UI not usable on macOS Big Sur Version 11.5.2

### ISSUE THREAD

**Issue by moreaki** [viewizard/astromenace#33]
A screenshot explains it much better:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/1086603/133333479-14e50a3b-f82c-4ae0-a905-44529e1bc858.png">

I'm using the latest (auto)-release: https://github.com/viewizard/astromenace/releases/download/1.4.2-1781/astromenace-osx.tar.gz

What could be the issue here?

**Comment by viewizard** [comment]
Looks like some OpenGL features declared as supported by drivers but not really supported by hardware. I see no issue with geometry rendering, so, for example, this could be GLSL shades issue...

**Comment by moreaki** [comment]
This is the output on the console when I start the game: [Console Output](https://pastebin.com/D0tMbDsT)

Do you reckon things would change if I attempted to compile it by myself?

**Comment by moreaki** [comment]
Also, it gets worse if I set the following:

```xml
<UseGLSL120 value="off" />
```

This is my configuration:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<AstroMenaceSettings>
    <!-- AstroMenace game Settings -->
    <MenuLanguage value="en" />
    <VoiceLanguage value="en" />
    <FontNumber value="0" />
    <DisplayIndex value="0" />
    <Width value="1024" />
    <Height value="640" />
    <Fullscreen value="off" />
    <!-- Common settings -->
    <MSAA value="4" />
    <CSAA value="4" />
    <VisualEffectsQuality value="0" />
    <AnisotropyLevel value="16" />
    <UseGLSL120 value="on" />
    <ShadowMap value="1" />
    <MaxPointLights value="6" />
    <MusicVolume value="8" />
    <SoundVolume value="10" />
    <VoiceVolume value="10" />
    <VSync value="0" />
    <Brightness value="5" />
    <ShowFPS value="off" />
    <WeaponPanelView value="3" />
    <GameSpeed value="1.500000" />
    <!-- Control settings -->
    <KeyBoardLeft value="Left" />
    <KeyBoardRight value="Right" />
    <KeyBoardUp value="Up" />
    <KeyBoardDown value="Down" />
    <KeyBoardPrimary value="Left Ctrl" />
    <KeyBoardSecondary value="Space" />
    <MousePrimary value="1" />
    <MouseSecondary value="3" />
    <JoystickPrimary value="0" />
    <JoystickSecondary value="1" />
    <JoystickNum value="0" />
    <JoystickDeadZone value="2" />
    <ControlSensivity value="5" />
    <MouseControl value="on" />
    <LastProfile value="-1" />
    <MenuScript value="0" />
    <!-- Tips and Hints settings -->
    <HintStatus1 value="on" />
    <HintStatus2 value="on" />
    <HintStatus3 value="on" />
    <HintStatus4 value="on" />
    <HintStatus5 value="on" />
    <HintStatus6 value="on" />
    <HintStatus7 value="on" />
    <HintStatus8 value="on" />
    <HintStatus9 value="on" />
    <HintStatus10 value="on" />
</AstroMenaceSettings>
```

**Comment by viewizard** [comment]
```
Vendor     : Intel Inc.
Renderer   : Intel(R) UHD Graphics 630
Version    : 2.1 INTEL-16.5.2
OpenGL Version    : 1.0
```
Not sure you could play with OpenGL version 1.0... this version number looks strange BTW, game need at least multi texturing that is part of OpenGL version 1.3 (without texturing you probably will see pictures that you have now).

As I know, Apple deprecated OpenGL long time ago in order to force developers use Metal instead... if old OpenGL (with fixed pipeline) support was removed (or broken) no way to fix it from game side.

> Do you reckon things would change if I attempted to compile it by myself?

You could try, but I believe you will have same result.

> Also, it gets worse if I set the following:

This is strange...

> This is my configuration:

 You could also try `<ShadowMap value="0" />`.

**Comment by moreaki** [comment]
This is my manual build output: [Build Output](https://pastebin.com/Y8s5fJtn)

The output after invoking the newly complied game is the same, so compiling and linking on my system does not change the issue.

**Comment by moreaki** [comment]
> ```
> Vendor     : Intel Inc.
> Renderer   : Intel(R) UHD Graphics 630
> Version    : 2.1 INTEL-16.5.2
> OpenGL Version    : 1.0
> ```
> 
> Not sure you could play with OpenGL version 1.0... this version number looks strange BTW, game need at least multi texturing that is part of OpenGL version 1.3 (without texturing you probably will see pictures that you have now).
>
> As I know, Apple deprecated OpenGL long time ago in order to force developers use Metal instead... if old OpenGL (with fixed pipeline) support was removed (or broken) no way to fix it from game side.

That could indeed be the issue.
 
> > Do you reckon things would change if I attempted to compile it by myself?
> 
> You could try, but I believe you will have same result.

Indeed.

> > Also, it gets worse if I set the following:
> 
> This is strange...
> 
> > This is my configuration:
> 
> You could also try `<ShadowMap value="0" />`.

Same same ;).

I fear that this is a lost cause, unless porting to Metal is feasible. But I doubt SDL2 supports Metal. Although some gist seems to indicate that it might work: https://gist.github.com/gcatlin/b89e0efed78dd91364609ca4095da346

**Comment by viewizard** [comment]
Game don't render by SDL2 (as I know, it have only 2D support), but use OpenGL directly. So, even if SDL2 will support Metal, someone will need write all render-related code that will use Metal.

> Or move to MoltenGL

We use OpenGL with fixed pipeline + shaders (optional, if shaders supported by hardware), need port it to OpenGL ES 2.0 first then... that also will be not so easy.

**Comment by moreaki** [comment]
> Game don't render by SDL2 (as I know, it have only 2D support), but use OpenGL directly. So, even if SDL2 will support Metal, someone will need write all render-related code that will use Metal.
> 
> > Or move to MoltenGL
> 
> We use OpenGL with fixed pipeline + shaders (optional, if shaders supported by hardware), need port it to OpenGL ES 2.0 first then... that also will be not so easy.

I see. That's a bit unfortunate, but such is life :).
