### ISSUE TITLE
Graphics issues on MBP 2019

### ISSUE THREAD

**Issue by KroArtem** [viewizard/astromenace#34]
## Expected Behavior
Astromenace runs smoothly on MacBook Pro 2019

## Actual Behavior
<img width="1792" alt="Screenshot 2023-01-20 at 1 00 12 PM" src="https://user-images.githubusercontent.com/1813101/214353301-952dff2b-f67f-45f0-ac61-a2ee12e3c244.png">

## Steps to Reproduce the Problem

  1. Compile Astromenace from source as being said in Readme
  2. Run Astromenace

## Specifications
[astromenace.txt](https://github.com/viewizard/astromenace/files/10492147/astromenace.txt)

  - Operating System (with version, if you know it):
    * macOS Ventura 13.1
  - Hardware Specifications (optional, if you know it):
    * 2.3 GHz 8-Core Intel Core i9
    * AMD Radeon Pro 5500M 4 GB
    * Intel UHD Graphics 630 1536 MB
  - Video Drivers (optional, if you know it):
    * ??
  - Game Version:
    * Latest master

What bothers me is that it says about software renderer:
```
Vendor     : Apple Computer Inc.
Renderer   : Software
Version    : 1.1
```

Files location:
[astromenace.zip](https://github.com/viewizard/astromenace/files/10492179/astromenace.zip)

**Comment by viewizard** [comment]
Look same as https://github.com/viewizard/astromenace/issues/33 issue.
Looks like Apple don't provide OpenGL drivers for hardware any more and software drivers don't support multitextures OpenGL feature (that is part of OpenGL version 1.3). Unfortunately, I have no chance to fix this issue.

**Comment by KroArtem** [comment]
That's unfortunate :/ Apple does some shitty decisions, sorry for my language. Maybe worth adding a note in Readme then?

**Comment by KroArtem** [comment]
[10 years ago](https://www.linux.org.ru/forum/games/8375796)  I had no problems running the game :) That was good old Linux, what a time
