### ISSUE TITLE
Flathub release?

### ISSUE THREAD

**Issue by nobody43** [viewizard/astromenace#36]
https://flathub.org/apps/com.viewizard.AstroMenace

Is it maintained by you? Should be mentioned in the README.

**Comment by viewizard** [comment]
> Is it maintained by you?

No, I don't maintain any distro/repo.

> Should be mentioned in the README.

Sure, will add to `Installation (Windows, macOS, Linux)` in README, thanks!

**Comment by viewizard** [comment]
Added in https://github.com/viewizard/astromenace/commit/2e61da95e029846cd89af714b33b4e66e90d67a9
